# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-06 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180405_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_value', models.CharField(max_length=264, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VocabResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', models.CharField(max_length=500)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.SearchV')),
            ],
        ),
    ]
