# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-06 13:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_searchv_vocabresults'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vocabresults',
            old_name='definition',
            new_name='nameV',
        ),
        migrations.RenameField(
            model_name='vocabresults',
            old_name='query',
            new_name='queryV',
        ),
    ]
